// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACxvqvtdqW69nsmLiip9_EhoBZkLvLx0M',
    appId: '1:807224230144:web:a0529ada52bfe8378133e5',
    messagingSenderId: '807224230144',
    projectId: 'app-lista-tarefa-f002d',
    authDomain: 'app-lista-tarefa-f002d.firebaseapp.com',
    storageBucket: 'app-lista-tarefa-f002d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSCB5UIe4blD_zooL200LvmACKYGnenE',
    appId: '1:807224230144:android:cf3635685280d73d8133e5',
    messagingSenderId: '807224230144',
    projectId: 'app-lista-tarefa-f002d',
    storageBucket: 'app-lista-tarefa-f002d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIXsJjCU15ccuk8vEgD9fYdXT088CSxmE',
    appId: '1:807224230144:ios:2353bdbe508979698133e5',
    messagingSenderId: '807224230144',
    projectId: 'app-lista-tarefa-f002d',
    storageBucket: 'app-lista-tarefa-f002d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
